version: "3"

networks: 
  loadbalancer0:
    driver: "bridge"

volumes:
  nginx_:
  certs_:

services:

  dummy:
    container_name: lb_haproxy_global
    image: alpine:latest
    networks:
      - loadbalancer0
    command: sh

  lb_traefik:
    container_name: lb_traefik_global
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - loadbalancer0
